import { PLUGIN_PREFIX } from '../../const';

const CORE_CONFIG_NAME = `${PLUGIN_PREFIX}/core` as const;
const CORE_CONFIG_NAME_SETUP = `${CORE_CONFIG_NAME}/setup` as const;
const CORE_CONFIG_NAME_SETUP_IMPORTS = `${CORE_CONFIG_NAME_SETUP}/imports` as const;
const CORE_CONFIG_NAME_RULES = `${CORE_CONFIG_NAME}/rules` as const;
const CORE_CONFIG_NAME_RULES_IMPORTS = `${CORE_CONFIG_NAME_RULES}/imports` as const;
const CORE_CONFIG_NAME_RULES_IMPORTS_WARNINGS = `${CORE_CONFIG_NAME_RULES_IMPORTS}/warnings` as const;
const CORE_CONFIG_NAME_RULES_IMPORTS_STATIC = `${CORE_CONFIG_NAME_RULES_IMPORTS}/static` as const;
const CORE_CONFIG_NAME_RULES_IMPORTS_STATIC_MARKDOWN = `${CORE_CONFIG_NAME_RULES_IMPORTS_STATIC}/markdown` as const;
const CORE_CONFIG_NAME_RULES_IMPORTS_STATIC_MARKDOWN_SOURCE =
	`${CORE_CONFIG_NAME_RULES_IMPORTS_STATIC_MARKDOWN}/source` as const;
const CORE_CONFIG_NAME_RULES_NODE = `${CORE_CONFIG_NAME_RULES}/node` as const;

type CoreConfigNames =
	| typeof CORE_CONFIG_NAME_RULES
	| typeof CORE_CONFIG_NAME_RULES_IMPORTS_STATIC
	| typeof CORE_CONFIG_NAME_RULES_IMPORTS_STATIC_MARKDOWN_SOURCE
	| typeof CORE_CONFIG_NAME_RULES_IMPORTS_WARNINGS
	| typeof CORE_CONFIG_NAME_RULES_NODE
	| typeof CORE_CONFIG_NAME_SETUP
	| typeof CORE_CONFIG_NAME_SETUP_IMPORTS;

export type { CoreConfigNames };

export {
	CORE_CONFIG_NAME_RULES,
	CORE_CONFIG_NAME_RULES_IMPORTS_STATIC,
	CORE_CONFIG_NAME_RULES_IMPORTS_STATIC_MARKDOWN_SOURCE,
	CORE_CONFIG_NAME_RULES_IMPORTS_WARNINGS,
	CORE_CONFIG_NAME_RULES_NODE,
	CORE_CONFIG_NAME_SETUP,
	CORE_CONFIG_NAME_SETUP_IMPORTS,
};
