import { PLUGIN_PREFIX } from '../../const';

const ASTRO_CONFIG_NAME = `${PLUGIN_PREFIX}/astro` as const;
const ASTRO_CONFIG_NAME_SETUP = `${ASTRO_CONFIG_NAME}/setup` as const;
const ASTRO_CONFIG_NAME_SETUP_PARSER = `${ASTRO_CONFIG_NAME_SETUP}/parser` as const;
const ASTRO_CONFIG_NAME_SETUP_PARSER_JAVASCRIPT = `${ASTRO_CONFIG_NAME_SETUP_PARSER}/javascript` as const;
const ASTRO_CONFIG_NAME_SETUP_PARSER_TYPESCRIPT = `${ASTRO_CONFIG_NAME_SETUP_PARSER}/typescript` as const;
const ASTRO_CONFIG_NAME_RULES = `${ASTRO_CONFIG_NAME}/rules` as const;

type AstroConfigNames =
	| typeof ASTRO_CONFIG_NAME_RULES
	| typeof ASTRO_CONFIG_NAME_SETUP
	| typeof ASTRO_CONFIG_NAME_SETUP_PARSER
	| typeof ASTRO_CONFIG_NAME_SETUP_PARSER_JAVASCRIPT
	| typeof ASTRO_CONFIG_NAME_SETUP_PARSER_TYPESCRIPT;

export type { AstroConfigNames };

export {
	ASTRO_CONFIG_NAME_RULES,
	ASTRO_CONFIG_NAME_SETUP,
	ASTRO_CONFIG_NAME_SETUP_PARSER,
	ASTRO_CONFIG_NAME_SETUP_PARSER_JAVASCRIPT,
	ASTRO_CONFIG_NAME_SETUP_PARSER_TYPESCRIPT,
};
