import { PLUGIN_PREFIX } from '../../const';

const MARKDOWN_CONFIG_NAME = `${PLUGIN_PREFIX}/markdown` as const;
const MARKDOWN_CONFIG_NAME_SETUP = `${MARKDOWN_CONFIG_NAME}/setup` as const;
const MARKDOWN_CONFIG_NAME_SETUP_PROCESSOR = `${MARKDOWN_CONFIG_NAME_SETUP}/processor` as const;
const MARKDOWN_CONFIG_NAME_SETUP_PARSER = `${MARKDOWN_CONFIG_NAME_SETUP}/parser` as const;

type MarkdownConfigNames =
	| typeof MARKDOWN_CONFIG_NAME_SETUP
	| typeof MARKDOWN_CONFIG_NAME_SETUP_PARSER
	| typeof MARKDOWN_CONFIG_NAME_SETUP_PROCESSOR;

export type { MarkdownConfigNames };

export { MARKDOWN_CONFIG_NAME_SETUP, MARKDOWN_CONFIG_NAME_SETUP_PARSER, MARKDOWN_CONFIG_NAME_SETUP_PROCESSOR };
