import { PLUGIN_PREFIX } from '../../const';

const TYPESCRIPT_CONFIG_NAME = `${PLUGIN_PREFIX}/typescript` as const;
const TYPESCRIPT_CONFIG_NAME_SETUP = `${TYPESCRIPT_CONFIG_NAME}/setup` as const;
const TYPESCRIPT_CONFIG_NAME_SETUP_PARSER = `${TYPESCRIPT_CONFIG_NAME_SETUP}/parser` as const;
const TYPESCRIPT_CONFIG_NAME_SETUP_PARSER_TYPEAWARE = `${TYPESCRIPT_CONFIG_NAME_SETUP_PARSER}/type-aware` as const;
const TYPESCRIPT_CONFIG_NAME_RULES = `${TYPESCRIPT_CONFIG_NAME}/rules` as const;
const TYPESCRIPT_CONFIG_NAME_RULES_DTS = `${TYPESCRIPT_CONFIG_NAME_RULES}/dts` as const;
const TYPESCRIPT_CONFIG_NAME_RULES_TYPEAWARE = `${TYPESCRIPT_CONFIG_NAME_RULES}/type-aware` as const;

type TypescriptConfigNames =
	| typeof TYPESCRIPT_CONFIG_NAME_RULES
	| typeof TYPESCRIPT_CONFIG_NAME_RULES_DTS
	| typeof TYPESCRIPT_CONFIG_NAME_RULES_TYPEAWARE
	| typeof TYPESCRIPT_CONFIG_NAME_SETUP
	| typeof TYPESCRIPT_CONFIG_NAME_SETUP_PARSER
	| typeof TYPESCRIPT_CONFIG_NAME_SETUP_PARSER_TYPEAWARE;

export type { TypescriptConfigNames };

export {
	TYPESCRIPT_CONFIG_NAME_RULES,
	TYPESCRIPT_CONFIG_NAME_RULES_DTS,
	TYPESCRIPT_CONFIG_NAME_RULES_TYPEAWARE,
	TYPESCRIPT_CONFIG_NAME_SETUP,
	TYPESCRIPT_CONFIG_NAME_SETUP_PARSER,
	TYPESCRIPT_CONFIG_NAME_SETUP_PARSER_TYPEAWARE,
};
