import {
	JSON_CONFIG_NAME_STYLISTIC_RULES_JSON_PACKAGE,
	JSON_CONFIG_NAME_STYLISTIC_RULES_JSON_TSCONFIG,
} from './json.config-name';
import { GLOB_JSON_PACKAGE, GLOB_JSON_TSCONFIG } from './json.globs';
import type { TypedFlatConfigItem } from './json.typed-config';

/**
 * Canonical key ordering for package.json and tsconfig.json files, applied on
 * top of the base json rules. In the meta-package this slice lives in the
 * stylistic concern and the sort-keys items move there with it.
 */
const JSON_SORT_KEYS_CONFIG: TypedFlatConfigItem[] = [
	{
		files: GLOB_JSON_PACKAGE,
		name: JSON_CONFIG_NAME_STYLISTIC_RULES_JSON_PACKAGE,
		rules: {
			'json/sort-array-values': [
				'error',
				{
					order: { type: 'asc' },
					pathPattern: '^files$',
				},
			],
			'json/sort-keys': [
				'error',
				{
					order: [
						'name',
						'displayName',
						'version',
						'author',
						'publisher',
						'description',
						'keywords',
						'categories',
						'repository',
						'homepage',
						'bugs',
						'funding',
						'license',
						'private',
						'publishConfig',
						'type',
						'sideEffects',
						'bin',
						'icon',
						'files',
						'main',
						'module',
						'unpkg',
						'jsdelivr',
						'types',
						'exports',
						'typesVersions',
						'scripts',
						'peerDependencies',
						'peerDependenciesMeta',
						'dependencies',
						'optionalDependencies',
						'devDependencies',
						'overrides',
						'resolutions',
						'engines',
						'packageManager',
						'pnpm',
						'activationEvents',
						'contributes',
						'husky',
						'simple-git-hooks',
						'lint-staged',
						'eslintConfig',
					],
					pathPattern: '^$',
				},
				{
					order: { type: 'asc' },
					pathPattern: '^(?:dev|peer|optional|bundled)?[Dd]ependencies(Meta)?$',
				},
				{
					order: { type: 'asc' },
					pathPattern: '^(?:resolutions|overrides|pnpm.overrides)$',
				},
				{
					order: { type: 'asc' },
					pathPattern: '^(?:scripts)$',
				},
				{
					order: ['types', 'import', 'require', 'default'],
					pathPattern: '^exports.*$',
				},
				{
					order: [
						// Client hooks only
						'pre-commit',
						'prepare-commit-msg',
						'commit-msg',
						'post-commit',
						'pre-rebase',
						'post-rewrite',
						'post-checkout',
						'post-merge',
						'pre-push',
						'pre-auto-gc',
					],
					pathPattern: '^(?:gitHooks|husky|simple-git-hooks)$',
				},
			],
		},
	},
	{
		files: GLOB_JSON_TSCONFIG,
		name: JSON_CONFIG_NAME_STYLISTIC_RULES_JSON_TSCONFIG,
		rules: {
			'json/sort-keys': [
				'error',
				{
					order: ['extends', 'compilerOptions', 'references', 'files', 'include', 'exclude'],
					pathPattern: '^$',
				},
				{
					order: [
						// Projects
						'incremental',
						'composite',
						'tsBuildInfoFile',
						'disableSourceOfProjectReferenceRedirect',
						'disableSolutionSearching',
						'disableReferencedProjectLoad',
						// Language and Environment
						'target',
						'jsx',
						'jsxFactory',
						'jsxFragmentFactory',
						'jsxImportSource',
						'lib',
						'moduleDetection',
						'noLib',
						'reactNamespace',
						'useDefineForClassFields',
						'emitDecoratorMetadata',
						'experimentalDecorators',
						// Modules
						'baseUrl',
						'rootDir',
						'rootDirs',
						'customConditions',
						'module',
						'moduleResolution',
						'moduleSuffixes',
						'noResolve',
						'paths',
						'resolveJsonModule',
						'resolvePackageJsonExports',
						'resolvePackageJsonImports',
						'typeRoots',
						'types',
						'allowArbitraryExtensions',
						'allowImportingTsExtensions',
						'allowUmdGlobalAccess',
						// JavaScript Support
						'allowJs',
						'checkJs',
						'maxNodeModuleJsDepth',
						// Type Checking
						'strict',
						'strictBindCallApply',
						'strictFunctionTypes',
						'strictNullChecks',
						'strictPropertyInitialization',
						'allowUnreachableCode',
						'allowUnusedLabels',
						'alwaysStrict',
						'exactOptionalPropertyTypes',
						'noFallthroughCasesInSwitch',
						'noImplicitAny',
						'noImplicitOverride',
						'noImplicitReturns',
						'noImplicitThis',
						'noPropertyAccessFromIndexSignature',
						'noUncheckedIndexedAccess',
						'noUnusedLocals',
						'noUnusedParameters',
						'useUnknownInCatchVariables',
						// Emit
						'declaration',
						'declarationDir',
						'declarationMap',
						'downlevelIteration',
						'emitBOM',
						'emitDeclarationOnly',
						'importHelpers',
						'importsNotUsedAsValues',
						'inlineSourceMap',
						'inlineSources',
						'mapRoot',
						'newLine',
						'noEmit',
						'noEmitHelpers',
						'noEmitOnError',
						'outDir',
						'outFile',
						'preserveConstEnums',
						'preserveValueImports',
						'removeComments',
						'sourceMap',
						'sourceRoot',
						'stripInternal',
						// Interop Constraints
						'allowSyntheticDefaultImports',
						'esModuleInterop',
						'forceConsistentCasingInFileNames',
						'isolatedModules',
						'preserveSymlinks',
						'verbatimModuleSyntax',
						// Completeness
						'skipDefaultLibCheck',
						'skipLibCheck',
					],
					pathPattern: '^compilerOptions$',
				},
			],
		},
	},
];

export default JSON_SORT_KEYS_CONFIG;
