import { PLUGIN_PREFIX } from '@hexadrop/eslint-config-shared';

const STYLISTIC_CONFIG_NAME = `${PLUGIN_PREFIX}/stylistic` as const;
const STYLISTIC_CONFIG_NAME_RULES = `${STYLISTIC_CONFIG_NAME}/rules` as const;
const STYLISTIC_CONFIG_NAME_RULES_JSON = `${STYLISTIC_CONFIG_NAME_RULES}/json` as const;
const STYLISTIC_CONFIG_NAME_RULES_JSON_PACKAGE = `${STYLISTIC_CONFIG_NAME_RULES_JSON}/package.json` as const;
const STYLISTIC_CONFIG_NAME_RULES_JSON_TSCONFIG = `${STYLISTIC_CONFIG_NAME_RULES_JSON}/tsconfig.json` as const;

export { STYLISTIC_CONFIG_NAME_RULES_JSON_PACKAGE, STYLISTIC_CONFIG_NAME_RULES_JSON_TSCONFIG };
