name: Check

on:
  workflow_call:

jobs:
  check:
    name: Code check
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        command: [ 'lint:ci', typecheck ]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: ESLint cache
        uses: actions/cache@v6
        if: matrix.command == 'lint:ci'
        with:
          path: .eslintcache
          key: ${{ runner.os }}-node

      - name: Build types
        run: bun build:types

      - name: ${{ matrix.command }}
        run: bun run ${{ matrix.command }}
