name: Continuous integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize ]

jobs:
  check:
    name: Check
    uses: hexadrop/github-workflows/.github/workflows/check.yml@v1.0.0
    with:
      commands: '["lint:ci", "typecheck", "test"]'
      cache-commands: '["lint:ci"]'
