name: Continuous integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize ]

jobs:
  check:
    uses: ./.github/workflows/check.yml
