name: "Release: stable"

on:
  push:
    branches: [ main ]

jobs:
  check:
    name: Check
    uses: hexadrop/github-workflows/.github/workflows/check.yml@v1
    with:
      commands: '["lint:ci", "typecheck"]'
      cache-commands: '["lint:ci"]'

  release-stable:
    name: Release
    needs: [ check ]
    uses: ./.github/workflows/release.yml
    with:
      snapshot: false
      concurrency-group: release
