name: "Release"

on:
  push:
    branches: [ main, develop ]

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml

  detect-changeset-change:
    name: Changeset
    if: github.ref == 'refs/heads/develop'
    uses: hexadrop/github-workflows/.github/workflows/detect-changeset-change.yml@v1

  publish:
    name: Publish
    needs: [ check, detect-changeset-change ]
    if: github.ref == 'refs/heads/main' || needs.detect-changeset-change.outputs.should_publish_beta == 'true'
    uses: hexadrop/github-workflows/.github/workflows/release.yml@v1
    with:
      snapshot: ${{ github.ref == 'refs/heads/develop' }}
      concurrency-group: release-${{ github.ref_name }}
