name: "Release: publish"

on:
  workflow_call:
    inputs:
      snapshot:
        required: false
        type: boolean
        default: false
      concurrency-group:
        required: true
        type: string
    outputs:
      published:
        description: 'Whether packages were published'
        value: ${{ jobs.publish.outputs.published }}

jobs:
  publish:
    name: "Publish ${{ inputs.snapshot && 'beta' || 'stable' }}"
    permissions:
      contents: 'write'
      id-token: 'write'
      issues: 'write'
      pull-requests: 'write'
    uses: hexadrop/github-workflows/.github/workflows/release.yml@v1
    with:
      snapshot: ${{ inputs.snapshot }}
      concurrency-group: ${{ inputs.concurrency-group }}
