name: "Release: beta"

on:
  push:
    branches: [ develop ]

jobs:
  check:
    name: Check
    uses: hexadrop/github-workflows/.github/workflows/check.yml@v1
    with:
      commands: '["lint:ci", "typecheck"]'
      cache-commands: '["lint:ci"]'

  detect-changeset-change:
    name: Changeset
    needs: [ check ]
    uses: hexadrop/github-workflows/.github/workflows/detect-changeset-change.yml@v1

  release-beta:
    name: Release
    needs: [ detect-changeset-change ]
    if: needs.detect-changeset-change.outputs.should_publish_beta == 'true'
    uses: ./.github/workflows/release.yml
    with:
      snapshot: true
      concurrency-group: release-beta
