name: Add changeset to Renovate updates

on:
  pull_request_target:
    types: [opened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  changesets:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot Changesets
        uses: feelepxyz/dependabot-changesets@v1
